################################################
#Algebraic invariants miscellanea
function RootsFromInvariants(g2,g3)
	return PolynomialRoots.roots([-g3,-g2,0,4])
end

function InvariantsFromRoots(Roots)
	g2 = -4*(Roots[1] * Roots[2] + Roots[2] * Roots[3] + Roots[1] * Roots[3])
	g3 = 4* Roots[1] * Roots[2] * Roots[3]
	return g2,g3
end

function JInvariantAndDiscriminant(g2,g3)
	D = g2^3 - 27*g3^2
	J = g2^3/D
	return J,D
end

################################################
#If the lattice is generated by u1 and u2, one of which is real and other one is purely imaginary
#normalize to have a basis where first term is positive and real, and the second one is positive and purely imaginary
function purify(z, e)
	r = real(z)
	i = imag(z)
	if(abs(r) < e)
		r = r * 0
	end
	if(abs(i) < e)
		i = i * 0
	end
	return r + im*i
end

function RectangularNormalization(u1, u2, e1, e2, e) #lattice basis and eta
	w1,w2 = purify(u1,e),purify(u2,e)
	f1,f2 = purify(e1,e),purify(e2,e)
	if abs(real(w2)) > e
		w1,w2 = w2,w1
		f1,f2 = f2,f1
	end
	s1,s2 = sign(real(w1)),sign(imag(w2))
	w1 = w1 * s1
	w2 = w2 * s2
	f1 = f1 * s1
	f2 = f2 * s2
	return w1,w2,f1,f2
end

################################################
#functions that perform operations with triples of roots
function LandenTranformOfRoots(roots, i)
	 e3 = roots[i]
	 e2 = roots[i%3 + 1]
	 e1 = roots[(i+1)%3 + 1]
	 return [-e3/2,  e3/4 - (5 * e3^2/8 - (e1^2 + e2^2)/8)^0.5, e3/4 + (5 * e3^2/8 - (e1^2 + e2^2)/8)^(0.5)]
end

function choose_root_min(roots)
	a = abs(roots[1] - roots[2])
	b = abs(roots[1] - roots[3])
	c = abs(roots[3] - roots[2])
	if a < b 
		if a < c
			return 3
		end
		return 1
	end
	if c < b
		return 1
	end
	return 2
end
	
function choose_root_mid(roots)
	j = choose_root_min(roots) #to guarantee that min and mid never coincide 
	a = abs(roots[j%3 + 1] - roots[j])
	b = abs(roots[(j+1)%3 + 1] - roots[j])
	if a < b
		return (j+1)%3 + 1
	end
	return j%3 + 1
end

function choose_root_max(roots)
    j = choose_root_min(roots)
    k = 0
    a = abs(roots[j%3 + 1] - roots[j])
	b = abs(roots[(j+1)%3 + 1] - roots[j])
	if a < b
		k = (j+1)%3 + 1
	else
	    k = j%3 + 1
    end
    return 6 - j - k
end

function smallest_dist(roots)
	j = choose_root_min(roots)
	return abs(roots[j%3 + 1] - roots[(j+1)%3 + 1])
end

######################################################
#Reduction of a complex number z to a fundamental parallelogram (parallelogram with center at 0) given a basis
@inline function shiftToFundamentalParallelogram(z,w1,w2)
	t1 = imag(z*conj(w2))/imag(w1 * conj(w2))
	t2 = -imag(z*conj(w1))/imag(w1 * conj(w2))
	n1 = floor(Int, t1)
	n2 = floor(Int, t2)
	d1 = t1 - floor(t1)
	d2 = t2 - floor(t2)
	if 2 * d1 > 1
		d1 = d1 - 1
		n1 = n1 + 1
	end
	if 2 * d2 > 1
		d2 = d2 - 1
		n2 = n2 + 1
	end
	return (d1*w1 + d2*w2, n1, n2)
end
